aws s3 cp lambda.zip s3://library-management-lambda-deploy-810100779511/lambda.zip

aws lambda update-function-code \
  --function-name library-management-backend \
  --s3-bucket library-management-lambda-deploy-810100779511 \
  --s3-key lambda.zip